### ISSUE TITLE
Change default staging configuration setting for funding

### ISSUE THREAD

**Issue by jeandemeusy** [hoprnet/ct-applications#26]
Now that auto-funding works, we need to set the funding parameters for **staging nodes** correctly to not drain funds into channels.

I would recommend using:
- `min_stake_threshold`: 0.05 HOPR
- `funding_amount`: 0.1 HOPR

**Comment by ausias-armesto** [comment]
The nodes have been funded with these values, which are the same in rpch. For the sake of simplicity I would propose to use the same values in all stage environments:
```
  strategies:
    - !Promiscuous
      max_channels: 10
      new_channel_stake: '100000 HOPR' # 1000 tickets
      network_quality_threshold: 0.4
      minimum_node_balance: '1000000 HOPR' # 10x new channel stake
      enforce_max_channels: true
    - !AutoFunding
      funding_amount: '100000 HOPR' # 1000 tickets
      min_stake_threshold: '10000 HOPR' # 100 tickets
    - !Aggregating
      aggregation_threshold: 100
      unrealized_balance_ratio: 0.9
      aggregation_timeout: 60
      aggregate_on_channel_close: true
    - !AutoRedeeming
      redeem_only_aggregated: true
```
